### ISSUE TITLE
Bug: Updating payment methods does not update supplier version, supplier is not considered updated

### ISSUE THREAD

**Issue by amoilanen** [Tripletex/tripletex-api2#107]
Updating supplier payment methods via API does not update supplier version and supplier is not considered "changed" when the "changedSince" parameter is used

### Steps to reproduce using Tripletex API 2.0:

1. Create a supplier
2. Update supplier payment methods 

**Expected:**

Supplier version is updated from 1 to 2.

**Observed:**

Supplier version is not changed and remains 1.

4. Fetch suppliers using the "changedSince" parameter giving it timestamp after step 1. but before step 2.

**Expected:**

Supplier is returned.

**Observed:**

Supplier is not returned.

### Detailed requests and responses for the steps

```bash
curl -X POST "https://api.tripletex.io/v2/supplier" \
     -u "0:$SESSION_TOKEN" \
     -H "Content-Type: application/json" \
     -d '{"name": "New supplier"}' | jq
```

```json
{
  "value": {
    "id": 13306932,
    "version": 1,
    "url": "api.tripletex.io/v2/supplier/13306932",
    "name": "New supplier",
    "organizationNumber": "",
    "supplierNumber": 20016,
    "customerNumber": 0,
    "isSupplier": true,
    "isCustomer": false,
    "isInactive": false,
    "email": "",
    "invoiceEmail": "",
    "overdueNoticeEmail": "",
    "phoneNumber": "",
    "phoneNumberMobile": "",
    "description": "",
    "isPrivateIndividual": false,
    "showProducts": false,
    "accountManager": null,
    "postalAddress": {
      "id": 32489552,
      "url": "api.tripletex.io/v2/address/32489552"
    },
    "physicalAddress": {
      "id": 32489551,
      "url": "api.tripletex.io/v2/address/32489551"
    },
    "deliveryAddress": null,
    "category1": null,
    "category2": null,
    "category3": null,
    "bankAccountPresentation": [],
    "currency": {
      "id": 1,
      "url": "api.tripletex.io/v2/currency/1"
    },
    "ledgerAccount": {
      "id": 34357795,
      "url": "api.tripletex.io/v2/ledger/account/34357795"
    },
    "language": "EN",
    "isWholesaler": false,
    "displayName": "New supplier (20016)",
    "locale": "en_GB",
    "website": ""
  }
}
```

```bash
curl -X PUT "https://api.tripletex.io/v2/supplier/13306932" \
     -H "Content-Type: application/json" \
     -u "0:$SESSION_TOKEN" \
     -d '{
           "bankAccountPresentation": [
               {
                   "iban": "NO3882000610190",
                   "bban": "82000610190",
                   "bic": "DNBANOKKXXX",
                   "country": {
                       "name": "NO"
                   }
               }
           ]
         }' | jq
```

```json
{
  "value": {
    "id": 13306932,
    "version": 1,
    "url": "api.tripletex.io/v2/supplier/13306932",
    "name": "New supplier",
    "organizationNumber": "",
    "supplierNumber": 20016,
    "customerNumber": 0,
    "isSupplier": true,
    "isCustomer": false,
    "isInactive": false,
    "email": "",
    "invoiceEmail": "",
    "overdueNoticeEmail": "",
    "phoneNumber": "",
    "phoneNumberMobile": "",
    "description": "",
    "isPrivateIndividual": false,
    "showProducts": false,
    "accountManager": null,
    "postalAddress": {
      "id": 32489552,
      "url": "api.tripletex.io/v2/address/32489552"
    },
    "physicalAddress": {
      "id": 32489551,
      "url": "api.tripletex.io/v2/address/32489551"
    },
    "deliveryAddress": null,
    "category1": null,
    "category2": null,
    "category3": null,
    "bankAccountPresentation": [
      {
        "iban": "NO3882000610190",
        "bban": "82000610190",
        "bic": "DNBANOKKXXX",
        "country": {
          "id": 161,
          "url": "api.tripletex.io/v2/country/161"
        },
        "provider": "AUTOPAY"
      }
    ],
    "currency": {
      "id": 1,
      "url": "api.tripletex.io/v2/currency/1"
    },
    "ledgerAccount": {
      "id": 34357795,
      "url": "api.tripletex.io/v2/ledger/account/34357795"
    },
    "language": "EN",
    "isWholesaler": false,
    "displayName": "New supplier (20016)",
    "locale": "en_GB",
    "website": ""
  }
}
```

```bash
curl -X GET "https://api.tripletex.io/v2/supplier?changedSince=2025-03-11T08:18:00Z&fields=bankAccountPresentation(iban,bban,bic,country)" \
     -H "Content-Type: application/json" \
     -u "0:$SESSION_TOKEN" | jq
```

```json
{
  "fullResultSize": 0,
  "from": 0,
  "count": 0,
  "versionDigest": "Checksum not yet supported for this endpoint",
  "values": []
}
```

**Comment by LarsVanderheydtVisma** [comment]
Hi, thanks for the report. We're looking into it

**Comment by LarsVanderheydtVisma** [comment]
Hi again, a fix has been merged. The version and update date will now update when bankAccountPresentation is added on the supplier

**Comment by amoilanen** [comment]
Great, thanks. The fix though has probably not yet been deployed to the test env? I tested  with https://api.tripletex.io/v2 and the old behavior is still present there at the moment. It might probably take some time before the fix gets deployed to the test env and to production?

**Comment by amoilanen** [comment]
Verified as fixed in the new test env https://api-test.tripletex.tech/ Thank you

**Comment by tlxtellef** [comment]
Just for information (and posterity) the old test environment at https://api.tripletex.io will not get any new updates and will be shut down in the future, so please move all testing over to the newer environment at https://api-test.tripletex.tech .

See https://developer.tripletex.no/exciting-update-welcome-to-our-new-api-test-environment/ for more information.
